# Generated by Django 2.0.1 on 2018-02-25 18:51

from django.db import migrations, models
import yamlfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadImage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('filename', models.CharField(default='face_no_id', max_length=128)),
                ('original_filename', models.CharField(default='no_name', max_length=128)),
                ('file', models.ImageField(upload_to='uploads/')),
                ('extension', models.CharField(max_length=10)),
                ('align', models.CharField(choices=[('L', 'left'), ('R', 'right')], default='L', max_length=1)),
                ('width', models.SmallIntegerField(default=0)),
                ('height', models.SmallIntegerField(default=0)),
                ('upload_date', models.DateTimeField(auto_now=True)),
                ('yaml_file', yamlfield.fields.YAMLField()),
            ],
        ),
    ]
