# Generated by Django 2.1.dev20171205201120 on 2017-12-12 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=128)),
                ('file', models.ImageField(upload_to='uploads/')),
                ('upload_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
