# Generated by Django 2.1.dev20171205201120 on 2017-12-13 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mechanism', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadimage',
            name='align',
            field=models.CharField(choices=[('L', 'left'), ('R', 'right')], default='L', max_length=1),
        ),
    ]
