# Generated by Django 2.1.dev20171205201120 on 2017-12-13 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mechanism', '0002_uploadimage_align'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadimage',
            name='original_filename',
            field=models.CharField(default='no_name', max_length=128),
        ),
        migrations.AlterField(
            model_name='uploadimage',
            name='filename',
            field=models.CharField(default='face_no_id', max_length=128),
        ),
        migrations.AlterField(
            model_name='uploadimage',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
