# Generated by Django 2.1.dev20171205201120 on 2017-12-13 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mechanism', '0003_auto_20171213_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadimage',
            name='extension',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
