# Generated by Django 2.1.dev20171205201120 on 2017-12-15 10:33

from django.db import migrations
import yamlfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mechanism', '0004_uploadimage_extension'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadimage',
            name='yaml_file',
            field=yamlfield.fields.YAMLField(default=' '),
            preserve_default=False,
        ),
    ]
