# Generated by Django 2.1.dev20171205201120 on 2017-12-15 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mechanism', '0005_uploadimage_yaml_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadimage',
            name='height',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='uploadimage',
            name='width',
            field=models.SmallIntegerField(default=0),
        ),
    ]
